var N = null;var sourcesIndex = {};
sourcesIndex["leptess"] = {"name":"","files":["capi.rs","leptonica.rs","lib.rs","tesseract.rs","variable.rs"]};
sourcesIndex["leptonica_plumbing"] = {"name":"","files":["borrowed_box.rs","borrowed_pix.rs","box.rs","boxa.rs","lib.rs","pix.rs"]};
sourcesIndex["leptonica_sys"] = {"name":"","files":["lib.rs"]};
sourcesIndex["proc_macro2"] = {"name":"","files":["detection.rs","fallback.rs","lib.rs","marker.rs","parse.rs","wrapper.rs"]};
sourcesIndex["quote"] = {"name":"","files":["ext.rs","format.rs","ident_fragment.rs","lib.rs","runtime.rs","spanned.rs","to_tokens.rs"]};
sourcesIndex["syn"] = {"name":"","dirs":[{"name":"gen","files":["clone.rs","gen_helper.rs"]}],"files":["attr.rs","await.rs","bigint.rs","buffer.rs","custom_keyword.rs","custom_punctuation.rs","data.rs","derive.rs","discouraged.rs","error.rs","export.rs","expr.rs","ext.rs","generics.rs","group.rs","ident.rs","lib.rs","lifetime.rs","lit.rs","lookahead.rs","mac.rs","macros.rs","op.rs","parse.rs","parse_macro_input.rs","parse_quote.rs","path.rs","print.rs","punctuated.rs","sealed.rs","span.rs","spanned.rs","thread.rs","token.rs","ty.rs","verbatim.rs"]};
sourcesIndex["tesseract_plumbing"] = {"name":"","files":["lib.rs","tess_base_api.rs","text.rs"]};
sourcesIndex["tesseract_sys"] = {"name":"","files":["lib.rs"]};
sourcesIndex["thiserror"] = {"name":"","files":["aserror.rs","display.rs","lib.rs"]};
sourcesIndex["thiserror_impl"] = {"name":"","files":["ast.rs","attr.rs","expand.rs","fmt.rs","generics.rs","lib.rs","prop.rs","valid.rs"]};
sourcesIndex["unicode_xid"] = {"name":"","files":["lib.rs","tables.rs"]};
createSourceSidebar();
